spring:
   data:
      mongodb:
         database: ${MONGO_DATABASE:madie}
         uri: ${MONGO_URI:mongodb://gakins:E5press0@localhost:27017/madie}?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000

server:
   servlet:
      context-path: /api
      
management:
   endpoints:
      enabled-by-default: false
   endpoint:
      health:
         enabled: true               
         