spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE:madie}
      uri: ${MONGO_URI:mongodb://${DBUSER}:${DBPASS}@localhost:27017/madie}?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000
      auto-index-creation: true

server:
  servlet:
    context-path: /api

madie:
  admin:
    concurrency-limit: ${MADIE_ADMIN_CONCURRENCY_LIMIT:5}
  allowedApi: http://localhost:9000
  json:
    resources:
      base-uri: ${MADIE_JSON_RESOURCES_BASE_URI:https://madie.cms.gov/}
  fhir:
    service:
      base-url: ${FHIR_SERVICES_URL:http://localhost:8085/api}
      hapi-fhir:
        measures:
          bundle-uri: /fhir/measures/bundles
          export-uri: /fhir/measures/export
        validation:
          bundle-uri: /fhir/validations/bundles
      test-cases: /fhir/test-cases
  cql-elm:
    service:
      base-url: ${ELM_TRANSLATOR_SERVICE_URL:http://localhost:8084/api}
      elm-json-uri: /cql/translator/cql
      elm-json-uri-for-mat-transferred-measure: /mat/translator/cqlToElm
  virus-scan:
    service:
      base-url: ${VIRUS_SCAN_SERVICE_URL:http://localhost:5000}
      scan-file-uri: /scan-file
      api-key: ${VIRUS_SCAN_SERVICE_APIKEY:1234567}
  terminology:
    service:
      base-url: ${TERMINOLOGY_SERVICE_URL:http://localhost:8082/api/vsac}
      fetch-value-sets: /value-sets/searches
      validate-codes: /validations/codes
  qdm-service:
    base-url: ${QDM_SERVICE_URL:http://localhost:8086/api}
    create-package-urn: /qdm/measures/package
  service-config:
    json-url: ${SERVICE_CONFIG_JSON_URL:http://localhost:9000/env-config/serviceConfig.json}


management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-18092578.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}

lambda-api-key: ${LAMBDA_API_KEY:9202c9fa}
organizations-api-key: ${ORGANIZATIONS_API_KEY:fa9c193c}
admin-api-key: ${ADMIN_API_KEY:0a51991c}

mongock:
  migration-scan-package:
    - cms.gov.madie.measure.config