spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE:madie}
      uri: ${MONGO_URI:mongodb://${DBUSER}:${DBPASS}@localhost:27017/madie}?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000


server:
  servlet:
    context-path: /api

madie:
  allowedApi: http://localhost:9000
  fhir:
    service:
      base-url: ${FHIR_SERVICES_URL:http://localhost:8085/api}
      hapi-fhir:
        measures:
          bundle-uri: /hapiFhir/measures/bundles
  cql-elm:
    service:
      base-url: ${ELM_TRANSLATOR_SERVICE_URL:http://localhost:8084/api}
      elm-json-uri: /cql/translator/cql

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-18092578.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}

lambda-api-key: ${LAMBDA_API_KEY:9202c9fa}

mongock:
  start-system-version: 1
  migration-scan-package:
    - cms.gov.madie.measure.changes
  enabled: true
  # read/write concerns should be changed for PROD
  mongo-db:
    read-concern: local
  test-enabled: false

hapi-fhir:
  url: ${HAPI_FHIR_URL:http://localhost:8087/fhir}
  patient:
    uri: /Patient
  bundle:
    uri: /Bundle
