spring:
  data:
    mongodb:
      database: admin
      uri: mongodb://root:E5press0@localhost:27017/madie?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000


server:
  servlet:
    context-path: /api

madie:
  allowedApi: http://localhost:9000

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

okta:
  oauth2:
    issuer: https://dev-18092578.okta.com/oauth2/default
    audience: api://default


mongock:
  start-system-version: 1
  migration-scan-package:
    - cms.gov.madie.measure.changes
  enabled: true
  # read/write concerns should be changed for PROD
  mongo-db:
    read-concern: local
  test-enabled: false
