name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      #- uses: actions/checkout@master
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: codecov/codecov-action@v2
        with:
          files: ./target/site/jacoco-merged-test-coverage-report/jacoco.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false) 
