name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: set environment variable
        id: set_okta
        run: echo “OKTA_ISSUER=https://dev-test.okta.com/oauth2/default” >> $GITHUB_ENV
      - name: test print
        id: print_okta
        run: echo “${{env.OKTA_ISSUER}}”
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
